spring:
  application:
    name: Todo           # Added space after colon
  datasource:
    url: jdbc:mysql://localhost:3306/SPRING
    username: root
    password: 'dumdum123'
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true       # Added space after colon
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true


server:
  port: 8081




